language: java
jdk:
  - oraclejdk8
  - openjdk8

install: true

scripts:
  - mvn cobertura:cobertura

cache:
  directories:
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)
